-- Add debug fields to research_jobs table

-- Add hypotheses field to store the generated search hypotheses
ALTER TABLE public.research_jobs
ADD COLUMN IF NOT EXISTS hypotheses jsonb DEFAULT '[]'::jsonb;

-- Add research timing fields
ALTER TABLE public.research_jobs
ADD COLUMN IF NOT EXISTS started_at timestamptz,
ADD COLUMN IF NOT EXISTS completed_at timestamptz;

-- Add column for credibility_story (missing from original schema)
ALTER TABLE public.research_jobs
ADD COLUMN IF NOT EXISTS credibility_story text;

COMMENT ON COLUMN public.research_jobs.hypotheses IS 'Search hypotheses generated by Gemini for content discovery';
COMMENT ON COLUMN public.research_jobs.started_at IS 'Timestamp when research execution actually started';
COMMENT ON COLUMN public.research_jobs.completed_at IS 'Timestamp when research completed (success or failure)';
